### ISSUE TITLE
Limpiar el código de necesidades, dejando solo las funcionalidades de este en el cliente

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/necesidades-cliente#1]
se requiere limpiar el cliente de necesidades de tal manera que solo se mantengan funcionalidades y rutas de este.

***proceso recomendado***
- [x] tener el cliente de `gaia_cliente` en local 
- [x] realizar un pull o checkout de las ramas
 - master
 - dev
 - pruebas
 - gaia_dev
- necesidades
 esto con el fin de que sean subidas al presente repositorio.
- [x] subir las ramas anterior mente nombradas al repo

***objetivos***
- [x] eliminar rutas no correspondientes a la sección de necesidades
 - cumplidos
 - resoluciones
- [x] eliminar funcionalidades ( scripts ) no correspondientes a la sección de necesidades
 - cumplidos
 - resoluciones
- [x] comprobar que aun se mantenga la funcionalidad del cliente de cumplidos.

---

***nota:***
este cliente no tiene la unificación con los clientes de resoluciones o cumplidos mas actualizados ya que genera incompatibilidad con estos, esto problema se deberá evaluar futuramente.

**Comment by anlramirezs11** [comment]
Quedó con un error que ya venía de la versión pasada y es que a veces no se vé el pdf de la necesidad
