### ISSUE TITLE
Quitar fechas de opción Hasta agotar presupuesto

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades-cliente#10]
Se debe 

- [x] Remover los campos de fecha en la opción _Hasta agotar presupuesto_ , ya que no debería haber un límite de tiempo. 

![image](https://user-images.githubusercontent.com/12780939/62571420-e9293180-b856-11e9-97e5-86fd2eb4197b.png)

**Comment by Soulfilip-UD** [comment]
Regalame PR asociado

**Comment by Soulfilip-UD** [comment]
Se reviso el commit asociado ! 

Tarea finalizada 
Proceeding to close Issue 👾
