### ISSUE TITLE
Mover campo supervisor de general a responsables

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades-cliente#11]
Se solicita

- [x] Mover el campo de Supervisor a la sección GENERAL del formulario de solicitar necesidad.

**Comment by macaguegi** [comment]
Se culmina esta tarea . Se solicita revisión a líder técnico @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Listo
Regalame el PR asociado

**Comment by Soulfilip-UD** [comment]
Se reviso el commit asociado ! 

Tarea finalizada 
Proceeding to close Issue 👾
