### ISSUE TITLE
Necesidades cliente: mover Financiación arriba dentro de General

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades-cliente#12]
- [x]  mover la seccion de financiacion mas arriba para que sea visible al finalizar de diligenciar general

**Comment by CarlosGutierrezArdila** [comment]
tarea finalizada a espera de revision de LT

**Comment by Soulfilip-UD** [comment]
Listo Carlos
Asociar el PR correspondiente

**Comment by Soulfilip-UD** [comment]
Se reviso el commit asociado ! 

Tarea finalizada 
Proceeding to close Issue 👾
