### ISSUE TITLE
Necesidades cliente: Marco legal - Al minimizar el menu , ocultar los textos también

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades-cliente#13]
- [x] Editar flujo de visualizacion del texto de marco legal

**Comment by CarlosGutierrezArdila** [comment]
tarea finalizada pendiente por revision LT

**Comment by Soulfilip-UD** [comment]
Listo Carlos
Anexar el PR correspodiente

**Comment by Soulfilip-UD** [comment]
Se reviso el commit asociado ! 

Tarea finalizada 
Proceeding to close Issue 👾
