### ISSUE TITLE
Agregar un tipo de contrato necesidad 

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades-cliente#14]
Se solicita :

- [x] Agregar opción 'Otros' al select de Tipo Contrato Necesidad

**Comment by macaguegi** [comment]
Se realiza inserción de tipo **Otros** en el API de pruebas ADMINISTRATIVA_SERVICE 
```json
  {
    "Nombre": "Otros",
    "Descripcion": "Tipo Contrato necesidad para otros \n",
    "CodigoAbreviacion": "OT",
    "Estado": true,
    "NumeroOrden": "5.00"
  }
```

**Comment by Soulfilip-UD** [comment]
Genial , que no se nos olvide .. que ya se realizo el proceso en tuleap para que los ingenieros de base de datos repliquen en la versión de producción.

Tarea finalizada

Proceeding to close Issue 👾
