### ISSUE TITLE
Ajustes de la sección Marco legal 

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades-cliente#15]
Se solicita :

- [x] Habilitar un botón con funcionalidad para subir un documento al marco legal :scroll:

**Comment by macaguegi** [comment]
Se socializa con líder técnico @Soulfilip-UD y aprueba los mockups para la funcionalidad de agregar documentos en el marco legal :heavy_check_mark: .  
![image](https://user-images.githubusercontent.com/12780939/62732489-11956500-b9ea-11e9-86e9-fc923a4420ff.png)

**Comment by macaguegi** [comment]
Se concluye el desarrollo del formulario . Queda pendiente definir modelo de datos para guardar los documentos que se van agregando al marco legal. Se solicita revisión de líder técnico @Soulfilip-UD . 💯

**Comment by Soulfilip-UD** [comment]
Gracias Maria Camila, Se revisan los mockups y se aprueban. 

Por favor asociame el PR en el que trabajaste el desarrollo

**Comment by macaguegi** [comment]
Se asocia el commit
[Commit](https://github.com/udistrital/necesidades-cliente/commit/71174392f37669deb1c33bb04d030fd9fe108aef#diff-00eea4fc8efba3ec621cfeb63beae01e)


![image](https://user-images.githubusercontent.com/12780939/62957075-b385ca80-bdb9-11e9-8d87-5ac2f333ddb0.png)

**Comment by Soulfilip-UD** [comment]
perfecto

tarea realizada al :100: 

Proceeding to close Issue :space_invader:
