### ISSUE TITLE
Compra -  Ajuste visual en Tabla de catálogo

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades-cliente#16]
Se solicita 

- [x] Modificar la tabla para que al listar los productos, que no se superponga el marco del listado y se pueda seleccionar

**Comment by macaguegi** [comment]
Se da por terminada esta tarea . Se solicita revisión de líder técnico @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Listo! 
PR porfa

**Comment by Soulfilip-UD** [comment]
Se reviso el commit asociado ! 

Tarea finalizada 
Proceeding to close Issue 👾
