### ISSUE TITLE
Definir modelo de datos  de necesidades a Kronos

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades-cliente#21]
- [x] revision de modelo de datos actual de administrativa
- [x] especificar entidades necesarias para necesidades

**Comment by macaguegi** [comment]
Se realiza un análisis del modelo actual con @CarlosGutierrezArdila y se documenta en el siguiente archivo 
[Modelo Necesidades](https://docs.google.com/spreadsheets/d/18XmRMWzXB4FXLskKbLrw7etChIk19AoeoBz6yndpx18/edit?usp=sharing)

Se solicita que líder @Soulfilip-UD revise el documento para aclarar cuestiones que interfieren en el modelo de mongo KRONOS :money_with_wings: :ru: .

**Comment by macaguegi** [comment]
Se crea una nueva entidad donde se registra la meta y actividades de una necesidad . Esta entidad se crea en un nuevo schema que sería parte de KRONOS y donde se guardará la información consignada en el formulario de **Financiación**.
![image](https://user-images.githubusercontent.com/12780939/63362748-f4d92580-c337-11e9-9a1e-1d0ef5cba013.png)

**Comment by macaguegi** [comment]
Se añade modelo en formato SQL y PNG En el repositorio de Financiera_documentación.

**Comment by Soulfilip-UD** [comment]
Modelo de Datos planteado, en el momento que llegue el momento se pondra en uso.

Buen trabajo, gracias por la documentación 
Proceeding to close Issue :space_invader:
