### ISSUE TITLE
necesidades_cliente: Integración de financiación con Kronos- Apropiaciones

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades-cliente#22]
- [x] crear servicio de plan cuentas M crud
- [x] utilizar los endpoints de apropiaciones 

 - 5 horas - Carlos

**Comment by CarlosGutierrezArdila** [comment]
Consultando con @juancsr  se definio que era necesario un endpoint que devolviera las apropiaciones hoja en un arreglo de la siguiente forma:
- Tipo: GET
- Params: Raiz, unidad ejecutora, Vigencia
- Respuesta:
```json
[
    {
      "Codigo": "3-8-95-8",
      "children": null,
      "data": {
        "Vigencia": 2019,
        "Nombre": "Rubro 3",
        "Descripcion": "Algo del rubro 3",
        "FechaCreacion": "2018-09-01T05:00:00Z",
        "FechaModificacion": "2018-09-01T05:00:00Z",
        "Activo": false,
        "Padre": "3",
        "UnidadEjecutora": "1",
        "Codigo": "3",
        "ApropiacionInicial": 0,
        "ApropiacionUtilizada": 0,
        "Movimientos": [],
        "Productos": {},
        "Estado": ""
      }
    },
	{
      "Codigo": "3-85-5-5",
      "children": null,
      "data": {
        "Vigencia": 2019,
        "Nombre": "Rubro 3",
        "Descripcion": "Algo del rubro 3",
        "FechaCreacion": "2018-09-01T05:00:00Z",
        "FechaModificacion": "2018-09-01T05:00:00Z",
        "Activo": false,
        "Padre": "5",
        "UnidadEjecutora": "1",
        "Codigo": "3",
        "ApropiacionInicial": 0,
        "ApropiacionUtilizada": 0,
        "Movimientos": [],
        "Productos": {},
        "Estado": ""
      }
    }
  ]
``` 
Se deja el cliente listo, apuntando a plan de cuentas mongo crud 254 para consumir el servicio, se cambiara el endpoint del request cuando este disponible.

**Comment by CarlosGutierrezArdila** [comment]
Tarea finalizada, se pueden ver las apropiaciones del servicio en el 254, pendiente revision del flujo de lista de apropiaciones en el controlador de solicitud_necesidad ya que el mismo al parecer no funciona correctamente , de esta corrección depende la terminación de las tareas #19 y #24 se pasa a revision de LT @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Entiendo
Tarea finalizada, gracias por la documentación. Muy buena :beer: 

Proceeding to close Issue :space_invader:
