### ISSUE TITLE
Modificar el tipo de contrato servicio, funciona como un catalogo

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades-cliente#25]
Se solicita : 

- [x] Cambiar el nombre de SERVICIO por CONTRATO DE PRESTACIÓN DE SERVICIOS

- [x] Cambiar el nombre de OTROS por SERVICIO

- [x] Al seleccionar un tipo de contrato  **SERVICIO** se debe cargar un formulario similar al que hay en COMPRA , es decir un catálogo de servicios .

**Comment by macaguegi** [comment]
Se agrega un catálogo como el de Compra y se quitan los campos "Unidad de Medida" y "Unidad" del detalle del servicio que se seleccionará. El catálogo que se carga todavía es el catálogo de productos que está en el servicio de Administrativa . Se cambiará cuando se tenga un modelo de datos definido . 
:money_mouth_face:

**Comment by macaguegi** [comment]
Estado de la tarea : Terminada .

**Comment by Soulfilip-UD** [comment]
Gracias @macaguegi  
Tarea revisaada y finalizada

Proceeding to close Issue :space_invader:
