### ISSUE TITLE
Habilitar botones de aprobación o rechazo de necesidad 

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades-cliente#30]
Se solicita : 

- [x] Ajustar los botones de Aprobación , Rechazo y Edición del cliente de necesidades

**Comment by macaguegi** [comment]
Estado : Terminada

**Comment by Soulfilip-UD** [comment]
Gracias Maria Camila,

Tarea realizada y socializda con el usuario como evidencia

Proceeding to close Issue 👾
