### ISSUE TITLE
necesidades_cliente: Corregir generar pdf - detalle de la  necesidad 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades-cliente#33]
- [x] revision flujo PDF
- [x] correcion de uso de Librerias y datos de generacion de PDF

**Comment by CarlosGutierrezArdila** [comment]
Se verifica que el PDF se genera bien y sin problema cuando los datos de la necesidad están perfectos, se espera a poder generar necesidades con datos validos desde el formulario

**Comment by CarlosGutierrezArdila** [comment]
Se suspende la optimizacion de generacion del PDF, en reunion con lideres de proyecto y arquitectos del 23/08/2019 se define que no es una tarea prioritaria ni necesaria para el desarrollo del hito actual, se procedera a ocultar la funcionalidad.

**Comment by Soulfilip-UD** [comment]
Validar con @mcrubianot

**Comment by Soulfilip-UD** [comment]
Al socializar con Maria C. , se estima que no se ha contado con que estas necesidades en pdf pueden ser solicitadas por entes de control , por lo que se llega al tema de documentos digitales, hablando con Carlos de funcionamiento, nos cuenta que la oficina tiene un plan de desarrollo respecto a los documentos digitales, de los que aún no se han definido lineamientos, pero que se estima que necesidades pueda adaptarse a estos.
Por lo que el desarrollo respecto a la generaciòn de necesidades como documentos pdf se congela, hasta que sea necesario como entregable y se espera que para ese momento se cuente con lineamientos para la documentacion y firma digital.

Se cierra el Issue :space_invader:
