### ISSUE TITLE
**necesidades_cliente** Autenticación  con wso2 -  5 horas - Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/necesidades-cliente#35]
- [x] Ajuste implicit token en servicio (https://github.com/udistrital/necesidades-cliente/commit/ff659d891c8d824f657a67d0150ffe299e46c80e)
- [x] Ajuste vista "no permission" (https://github.com/udistrital/necesidades-cliente/commit/318a84adba4189e76399ee09bbe4b96989c86025)

**Comment by miguelramirez93** [comment]
se realiza PR a una rama diferente a dev ya que la base de esta es la rama f/configuracion

**Comment by miguelramirez93** [comment]
Se agrega interceptor para cabeceras http globales (https://github.com/udistrital/necesidades-cliente/commit/26e20a6da14fb372952449f6c119c4905f3b81e5)

**Comment by miguelramirez93** [comment]
Tarea finalizada @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Tarea revisada y se puede evidenciar la autenticación en la versión desplegada

Proceeding to close Issue 👾
