### ISSUE TITLE
Ajuste de formulario de 'compra y servicio'

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades-cliente#44]
Como se acordó en la socialización #26: 

> Al desplegar clase de contratación ' Compra y servicio' esta parte de formulario, debe tener el catalogo de compras, retirar las opciones para especificar el perfil de la persona, y anexar un select que liste el tipo de servicio (este se alimenta de un servicio ya creado)

- [x] Mostrar el catálogo de compras

- [x] Retirar opciones de PERFIL

- [x] Listar en un select el tipo de Servicio

:octocat:

**Comment by macaguegi** [comment]
Se concluye esta tarea (Estado 100%) . Se solicita la revisión de líder técnico @Soulfilip-UD . :ru:

**Comment by Soulfilip-UD** [comment]
Recuerden asociar un PR para la revisión , 
Tarea revisada: la vista fue revisada paso a paso y se distinguen los cambios

Proceeding to close Issue 👾
