### ISSUE TITLE
necesidades_cliente: Validación de formularios por sección  

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades-cliente#45]
- [x] crear variables de control en el componente
- [x] verificar dependencias entre los steps 
- [x] ajustar las acciones para avanzar y retroceder en el formulario
- 8 horas - Carlos

**Comment by Soulfilip-UD** [comment]
Código muy limpio en el PR #50 , bien hecho

Tarea revisada y finalizada
Proceeding to close Issue 👾
