### ISSUE TITLE
Confirmar Conexión WSO2 **necesidades_cliente** 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades-cliente#5]
- [x] Confirmar Conexión WSO2 
- 1/2 hora - Carlos

**Comment by CarlosGutierrezArdila** [comment]
Se crea la conexión en WSO2 
![image](https://user-images.githubusercontent.com/32855979/62230553-a7484900-b387-11e9-9165-27e99b418b7e.png) se finaliza la tarea

**Comment by CarlosGutierrezArdila** [comment]
tarea finalizada a espera de revision LT @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Crearemos un issue en el que se tome la autenticación desde el cliente

Tarea Realizada
Proceeding to close Issue :space_invader:
