### ISSUE TITLE
Despliegue  sobre LocalOAS 

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades-cliente#6]
Se solicita : 
- [x] Realizar el despliegue del cliente de necesidades sobre el ambiente de pruebas.

**Comment by macaguegi** [comment]
Se encuentra desplegado en el ambiente de pruebas el cliente de necesidades. Se solicita revisión de líder técnico @Soulfilip-UD .

**Comment by Soulfilip-UD** [comment]
Tarea revisada, perfecto :100: 

Proceeding to close Issue :space_invader:
