### ISSUE TITLE
Ajustar routing de la app

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades-cliente#8]
Arreglar las rutas de la aplicación para visualizar solicitud necesidad

**Comment by macaguegi** [comment]
Se da por terminada esta tarea ya que se puede acceder al formulario de solicitar necesidad a través de la ruta **/necesidad/solicitud_necesidad** , se hicieron modificaciones en la dependencia LODASH. Se solicita a líder técnico @Soulfilip-UD la revisión de este issue.

**Comment by Soulfilip-UD** [comment]
Se reviso el commit asociado ! 

Tarea finalizada 
Proceeding to close Issue 👾
