### ISSUE TITLE
Necesidades cliente: Ocultar primer radio - avance /necesidad/solicitud_necesidad (form)

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades-cliente#9]
- [x] Ajustar opciones en la visualización del cliente

**Comment by CarlosGutierrezArdila** [comment]
Tarea finalizada, pendiente por revision de LT @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Listo Carlos
Anexar el PR correspondiente para la revisión

**Comment by Soulfilip-UD** [comment]
Se reviso el commit asociado ! 

Tarea finalizada 
Proceeding to close Issue 👾
